{{- if .Values.frontEnd.ingress.enabled -}}
{{- $name := include "amundsen.fullname" . }}

apiVersion: {{ include "amundsen.ingress.apiVersion" . }} 
kind: Ingress
metadata:
  name: {{ include "amundsen.fullname" . }}-{{ .Values.frontEnd.serviceName }}
  labels:
    app.kubernetes.io/component: {{ .Values.frontEnd.serviceName }}
    app.kubernetes.io/name: {{ include "amundsen.name" . }}
    helm.sh/chart: {{ include "amundsen.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}

  annotations:
{{- range $key, $value := .Values.frontEnd.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
{{- end }}
spec:
  rules:
    {{- range $host := .Values.frontEnd.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
        - path: {{ $.Values.frontEnd.ingress.path }}
          backend:
            serviceName: {{ $name }}-{{ $.Values.frontEnd.serviceName }}
            servicePort: frontendport
    {{- end -}}
  {{- if .Values.frontEnd.ingress.tls }}
  tls:
  {{- range .Values.frontEnd.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end -}}
{{- end -}}
