---
# Setup max number of unavailable pods in StatefulSet
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "clickhouse-keeper.fullname" . }}-pod-disruption-budget
  labels:
    {{- include "clickhouse-keeper.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "clickhouse-keeper.labels" . | nindent 6 }}
  maxUnavailable: 1
