---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "clickhouse-keeper.service-name" . }}
  labels:
    {{- include "clickhouse-keeper.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: raft
      protocol: TCP
      name: raft
  selector:
    {{- include "clickhouse-keeper.selectorLabels" . | nindent 4 }}
