---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "clickhouse-keeper.fullname" . }}
  labels:
    {{- include "clickhouse-keeper.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 2181
      name: client
    - port: {{ .Values.service.port }}
      name: prometheus
  selector:
    {{- include "clickhouse-keeper.selectorLabels" . | nindent 4 }}
