chart-dirs:
  - .
debug: true
remote: origin
chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami
  - stable=https://kubernetes-charts.storage.googleapis.com/
  - elastic=https://helm.elastic.co/
