chart-dirs:
  - .
check-version-increment: false
debug: true
remote: origin
validate-chart-schema: true
validate-maintainers: true
validate-yaml: true
chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami
  - stable=https://kubernetes-charts.storage.googleapis.com/
  - elastic=https://helm.elastic.co/
