apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    {{- range $key, $val := .Values.shufflePodLabels }}
    {{ $key }}: {{ $val }}
    {{- end }}
  name: {{ template "spark-shuffle.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  template:
    metadata:
      labels:
        {{- range $key, $val := .Values.shufflePodLabels }}
        {{ $key }}: {{ $val }}
        {{- end }}
    spec:
      volumes:
        - name: temp-volume
          hostPath:
            path: '/tmp/spark-local' # change this path according to your cluster configuration.
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}/{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: '/tmp/spark-local'
              name: temp-volume
              # more volumes can be mounted here.
              # The spark job must be configured to use these
              # mounts using the configuration:
              #   spark.kubernetes.shuffle.dir=<mount-1>,<mount-2>,...
          resources:
{{ toYaml .Values.resources | indent 12 }}
      serviceAccount: {{ .Values.global.serviceAccount | default .Values.serviceAccount }}

      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{ toYaml . | indent 8 | trim }}
      {{- end }}

      {{- with $.Values.affinity }}
      affinity:
        {{ toYaml . | indent 8 | trim }}
      {{- end }}
