apiVersion: v2
name: spark-shuffle
description: A Helm chart to deploy Spark shuffle service daemon set for Kubernetes
version: 0.2.0
appVersion: "3.3.0"
home: https://github.com/duyet/charts/tree/master/spark-shuffle-service
maintainers:
  - name: duyet
    email: me@duyet.net
    url: https://github.com/duyet/
