{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "zeppelin.serviceAccountName" . }}
  labels:
    {{- include "zeppelin.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "zeppelin.roleName" . }}
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps"]
  verbs: ["create", "get", "update", "patch", "list", "delete", "watch"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings"]
  verbs: ["bind", "create", "get", "update", "patch", "list", "delete", "watch"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "zeppelin.roleBindingName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "zeppelin.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "zeppelin.roleName" . }}
  apiGroup: rbac.authorization.k8s.io

{{- end }}
