apiVersion: v2
name: commento
description: A Helm chart to deploy Commento.io
version: 0.2.0
appVersion: "1.8.0"
home: https://github.com/duyet/charts/tree/master/commento
maintainers:
  - name: duyet
    email: me@duyet.net
    url: https://github.com/duyet/
dependencies:
  - name: postgresql
    version: 18.7.3
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
