{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "scheduling-restart.serviceAccountName" . }}
  labels:
    {{- include "scheduling-restart.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}


roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "scheduling-restart.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "scheduling-restart.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}

{{- end }}
