{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "scheduling-restart.serviceAccountName" . }}
  labels:
    {{- include "scheduling-restart.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  - apiGroups: ["apps", "extensions"]
    resources: ["deployments", "statefulset"]
    resourceNames: ["*"]
    verbs: ["get", "patch"]
{{- end }}
