apiVersion: v2
name: glossary
description: A [Glossary API](https://github.com/duyet/glossary) Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: 0.1.0
home: https://github.com/duyet/charts/tree/master/glossary
maintainers:
  - name: duyet
    email: me@duyet.net
    url: https://github.com/duyet
