apiVersion: v1
kind: Secret
metadata:
  name: {{ template "pgbouncer.fullname" . }}-secret
  labels:
    {{- include "pgbouncer.labels" . | nindent 4 }}
type: Opaque
data:
  userlist.txt: |-
{{ include "userlist.txt.1.0.0" . | b64enc | indent 4 }}
  pgbouncer.ini: |-
{{ include "pgbouncer.ini.1.0.0" . | b64enc | indent 4 }}
