apiVersion: v1
kind: Secret
metadata:
  name: {{ template "pgbouncer.fullname" . }}-secret
  labels:
    app.kubernetes.io/name: {{ include "pgbouncer.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "pgbouncer.chart" . }}
type: Opaque
data:
  userlist.txt: |-
{{ include "userlist.txt.1.0.0" . | b64enc | indent 4 }}
  pgbouncer.ini: |-
{{ include "pgbouncer.ini.1.0.0" . | b64enc | indent 4 }}
