# Deployment values for pgbouncer
replicaCount: 1
internalPort: 5432
antiAffinity: soft
# optionally define nodeAffinity
nodeAffinity: {}
# optionally define tolerations
tolerations: []

budget:
  # PodDisruptionBudget spec.minAvailable
  minAvailable: 0

image:
  repository: cradlepoint/pgbouncer
  tag: latest
  pullPolicy: Always

databases: {}
#  name:
#    host: host
#    port: port
#    user: user
#    dbname: dbname

users: {}
#  username: password

# Custom pgbouncer.ini
settings:
  auth_type: plain
  auth_query: "SELECT usename, passwd FROM pg_shadow WHERE usename=$1"

connectionLimits:
  maxClientConn: 200
  defaultPoolSize: 200
  minPoolSize: 15
  reservePoolSize: 25
  reservePoolTimeout: 5

spec:
  # Add custom pod labels here
  labels: {}
  annotations:
    {}
    # Add custom pod annotations here
    # Annotations are converted to a JSON string and run through
    # the helm `tpl` function. Then converted back to a map and
    # rendered as YAML. This allows usage of go template directives
    # in your annotations.

# Add custom deployment labels here
labels: {}

logConnections: 0
logDisconnections: 0
logStats: 0
logPoolerErrors: 1
verbose: 0
statsPeriod: 60

# add key: value map entries to customSettings to be added to pbgouncer.ini [pgbouncer] section
customSettings: {}

# Service configuration
service:
  enabled: false
  type: ClusterIP
  name: ""
  port: 5432
  annotations: {}

global:
  # optionally use namespace as dbname
  namespacedDatabases: false

tls:
  #secretName: pgbouncer-tls
  client:
    enabled: false
    sslmode: prefer
    key: "tls.key"
    cert: "tls.crt"
    ciphers: fast
    tlsProtocols: secure
    dheParams: auto
    ecdhCurve: auto
  server:
    enabled: false
    sslmode: prefer
