apiVersion: {{ include "commento.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "commento.fullname" . }}
  labels:
    {{- include "commento.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "commento.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- if .Values.podAnnotations }}
        {{ toYaml .Values.podAnnotations | nindent 8 }}
        {{- end }}
      labels:
        {{- include "commento.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      containers:
      - name: commento
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP

        envFrom:
          - secretRef:
              name: {{ include "commento.fullname" . }}

        env:
          - name: COMMENTO_ORIGIN
            value: {{ default .Release.Name .Values.originUrl | quote }}

          {{- if .Values.postgresql.enabled }}
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ if .Values.existingSecret }}{{ .Values.existingSecret }}{{else}}{{ include "commento.fullname" . }}{{ end }}
                key: postgresql-password
          - name: COMMENTO_POSTGRES
            value: "postgres://postgres:$(POSTGRES_PASSWORD)@{{ .Release.Name }}-postgresql:5432/{{ .Values.postgresql.postgresqlDatabase }}?sslmode=disable"
          {{- end }}

          - name: COMMENTO_PORT
            value: "8080"
          - name: COMMENTO_FORBID_NEW_OWNERS
            value: "{{ if .Values.dashboardRegistration }}false{{ else }}true{{ end }}"

          {{- if .Values.cdn.enabled }}
          - name: COMMENTO_CDN_PREFIX
            value: {{ .Values.cdn.cdnPrefix | quote }}
          {{- end }}

          {{- with .Values.smtp }}
          - name: COMMENTO_SMTP_HOST
            value: {{ .host | quote }}
          - name: COMMENTO_SMTP_PORT
            value: {{ .port | quote }}
          - name: COMMENTO_SMTP_USERNAME
            value: {{ .username | quote }}
          - name: COMMENTO_SMTP_PASSWORD
            value: {{ .password | quote }}
          - name: COMMENTO_SMTP_FROM_ADDRESS
            value: {{ .fromAddress | quote }}
          {{- end }}

          {{- with .Values.akismetKey }}
          - name: COMMENTO_AKISMET_KEY
            value: {{ . | quote }}
          {{- end }}

          {{- if .Values.googleOAuth.enabled }}
          - name: COMMENTO_GOOGLE_KEY
            value: {{ .Values.googleOAuth.key | quote }}
          - name: COMMENTO_GOOGLE_SECRET
            value: {{ .Values.googleOAuth.secret | quote }}
          {{- end }}

          {{- if .Values.githubOAuth.enabled }}
          - name: COMMENTO_GITHUB_KEY
            value: {{ .Values.githubOAuth.key | quote }}
          - name: COMMENTO_GITHUB_SECRET
            value: {{ .Values.githubOAuth.secret | quote }}
          {{- end }}

          {{- if .Values.gitlabOAuth.enabled }}
          - name: COMMENTO_GITLAB_KEY
            value: {{ .Values.gitlabOAuth.key | quote }}
          - name: COMMENTO_GITLAB_SECRET
            value: {{ .Values.gitlabOAuth.secret | quote }}
          {{- end }}

          {{- if .Values.twitterOAuth.enabled }}
          - name: COMMENTO_TWITTER_KEY
            value: {{ .Values.twitterOAuth.key | quote }}
          - name: COMMENTO_TWITTER_SECRET
            value: {{ .Values.twitterOAuth.secret | quote }}
          {{- end }}

          {{- range $key, $value :=  .Values.extraEnvs }}
          {{- if $value }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
          {{- end }}


        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
