{{- if (include "commento.createSecret" .) }}
{{ $randPassword := randAlphaNum 20 }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "commento.fullname" . }}
  labels:
    {{- include "commento.labels" . | nindent 4 }}
type: Opaque
data:
  {{ if .Values.postgresql.postgresqlPassword }}
  postgresql-password: {{ default "" .Values.postgresql.postgresqlPassword | b64enc | quote }}
  {{ else }}
  postgresql-password: {{ $randPassword | b64enc | quote }}
  {{ end }}
{{- end -}}
