{{- if (include "commento.createSecret" .) }}
{{ $randPassword := randAlphaNum 20 }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "commento.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "commento.name" . }}
    helm.sh/chart: {{ include "commento.chart" . }}
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
type: Opaque
data:
  {{ if .Values.postgresql.postgresqlPassword }}
  postgresql-password: {{ default "" .Values.postgresql.postgresqlPassword | b64enc | quote }}
  {{ else }}
  postgresql-password: {{ $randPassword | b64enc | quote }}
  {{ end }}
{{- end -}}
