apiVersion: v1
kind: Secret
metadata:
  name: {{ include "commento.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "commento.name" . }}
    helm.sh/chart: {{ include "commento.chart" . }}
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
type: Opaque
data:
  {{ if .Values.postgresql.postgresqlPassword }}
  POSTGRES_PASSWORD: {{ default "" .Values.postgresql.postgresqlPassword | b64enc | quote }}
  {{ else }}
  POSTGRES_PASSWORD: {{ randAlphaNum 20 | b64enc | quote }}
  {{ end }}