name: Chart Lint

on: [push, pull_request]

jobs:
  chart-lint:
    runs-on: ubuntu-latest

    # Multiple KinD version
    strategy:
      matrix:
        helm_version: [v3.4.0]
        k8s_version: [v1.20.15, v1.22.5]

    steps:
    - name: Checkout
      uses: actions/checkout@v3.3.0

    - name: Fetch history
      run: git fetch --prune --unshallow

    - name: Set up Helm
      uses: azure/setup-helm@v3.5
      with:
        version: ${{ matrix.helm_version }}

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.7

    - name: Set up chart-testing
      uses: helm/chart-testing-action@v2.3.1

    - name: Run chart-testing (list-changed)
      id: list-changed
      run: |
        changed=$(ct list-changed)
        if [[ -n "$changed" ]]; then
          echo "::set-output name=changed::true"
        fi

    - name: Run chart-testing (lint)
      id: lint
      run: ct lint --config .github/ct-lint.yaml

    - name: Create KinD cluster
      uses: helm/kind-action@v1.5.0
      with:
        kubectl_version: ${{ matrix.k8s_version }}
        node_image: kindest/node:${{ matrix.k8s_version }}
      # if: steps.list-changed.outputs.changed == 'true'

    - name: Run chart-testing (install)
      run: ct install --config .github/ct-install.yaml
